In [1]:
import torch

In [2]:
x = torch.arange(12,dtype=torch.float32).reshape([3,4])

In [3]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
y = torch.randn([3,4])

In [5]:
y

tensor([[-0.3778,  1.2330,  0.8986, -0.4782],
        [ 1.0941,  0.2191, -0.0952,  0.5960],
        [-0.1325, -0.3410, -0.2877,  0.2180]])

In [6]:
z = torch.cat((x,y),dim=1) # dim=0表示横插，dim=1表示纵插

In [7]:
(x.reshape(12)+y.reshape((12,1))).shape # 广播机制

torch.Size([12, 12])

In [8]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
y.sum()

tensor(2.5462)

In [10]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
before = id(y)
y[:] = y + x # y[:]可以减少内存开销， y+=x也可以实现这一点

In [12]:
id(y) == before

True

In [13]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [14]:
# 将大小为1的张量转换为python标量，可以调用item函数或者python内置函数

In [15]:
B[1,1].item()

5.0

In [16]:
x < y

tensor([[False,  True,  True, False],
        [ True,  True, False,  True],
        [False, False, False,  True]])

In [17]:
x1 = torch.arange(2).reshape((2,1,1))
x2 = torch.arange(2).reshape((1,1,2))

In [18]:
x1

tensor([[[0]],

        [[1]]])

In [19]:
x2

tensor([[[0, 1]]])

In [20]:
x1 + x2

tensor([[[0, 1]],

        [[1, 2]]])

In [21]:
import os
# 创建data文件夹
os.makedirs(os.path.join('data'),exist_ok=True)
data_file = os.path.join('data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,12750\n') # 填充数据
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,14000\n')

In [22]:
import pandas as pd

In [23]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave   12750
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN   14000


In [24]:
inputs, outputs = data.iloc[:,0:2],data.iloc[:,2]

In [25]:
inputs = inputs.fillna(inputs.mean())

C:\Users\wily_elite\AppData\Local\Temp\ipykernel_6640\64727764.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [26]:
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [27]:
inputs = pd.get_dummies(inputs,dummy_na=True)

In [28]:
inputs,outputs

(   NumRooms  Alley_Pave  Alley_nan
 0       3.0           1          0
 1       2.0           0          1
 2       4.0           0          1
 3       3.0           0          1,
 0     12750
 1    106000
 2    178100
 3     14000
 Name: Price, dtype: int64)

In [29]:
inputs,outputs = torch.tensor(inputs.values),torch.tensor(outputs.values)

In [30]:
inputs, outputs

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([ 12750, 106000, 178100,  14000]))

In [31]:
x1 = torch.tensor(3.0)
x2 = torch.tensor(2.0)

In [32]:
x1 + x2, x1 * x2, x1 / x2, x1 ** x2

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [33]:
len(inputs), inputs.shape

(4, torch.Size([4, 3]))

In [34]:
inputs.size()

torch.Size([4, 3])

In [35]:
inputs

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [36]:
inputs.T

tensor([[3., 2., 4., 3.],
        [1., 0., 0., 0.],
        [0., 1., 1., 1.]], dtype=torch.float64)

In [37]:
x1 = torch.arange(12,dtype=torch.float32).reshape((3,4))
x2 = torch.arange(12,dtype=torch.float32).reshape((3,4))

In [38]:
x1 * x2 # Hadamard 乘积，按元素乘法

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [39]:
a = 2

In [40]:
a + x1

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.]])

In [41]:
a * x1.sum()

tensor(132.)

In [42]:
x1

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
x1_axis_1 = x1.sum(axis = 1)
x1_axis_0 = x1.sum(axis = 0)
x1_axis_all = x1.sum(axis = [0,1])

In [44]:
x1_axis_all

tensor(66.)

In [45]:
x1.mean(axis = 0),x1.shape

(tensor([4., 5., 6., 7.]), torch.Size([3, 4]))

In [46]:
sum_x1 = x1.sum(axis = 1)
sum_x1 # 变成一个轴

tensor([ 6., 22., 38.])

In [47]:
sum_x1_keep_axis = x1.sum(axis = 1,keepdim = True)
sum_x1_keep_axis # 保持轴数不变，还是原来这些

tensor([[ 6.],
        [22.],
        [38.]])